### ISSUE TITLE
TTNMapper broken

### ISSUE THREAD

**Issue by icepicknz** [ttnmapper/tile-map-server#1]
Hi,

The last 2 days it appears TTNMapper has been broken, nothing showing up on the beta heat map and I cant bring up anything in advanced maps for specific devices either. Its like the DB server has been disconnected and not able to pull the data and plot? Tried on multiple browsers and devices.

**Comment by jpmeijers** [comment]
Let's continue discussion on https://github.com/ttnmapper/ttnmapper-web/issues/14
